feat: Layout and triggering of StickerPicker floating window
halo-sigs/plugin-sticker pull request #1
Opened 2024-07-21 17:41 UTC by AirboZH

2024-07-22 03:08 UTC, LIlGG requested changes

2024-07-22 03:08 UTC, LIlGG commented on src/main/java/run/halo/starter/StarterPlugin.java
> +public class StarterPlugin extends BasePlugin {
建议将类名改为 `StickerPlugin`
```suggestion
public class StickerPlugin extends BasePlugin {
```

2024-07-22 03:08 UTC, LIlGG commented on src/main/java/run/halo/starter/StarterPlugin.java
> +    }
删除无用的代码

```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on src/main/resources/plugin.yaml
> +  name: starter
修改插件名称

```suggestion
  name: plugin-sticker
```

2024-07-22 03:08 UTC, LIlGG commented on src/main/resources/plugin.yaml
> +  requires: ">=2.11.0"
```suggestion
  requires: ">=2.17.0"
```

2024-07-22 03:08 UTC, LIlGG commented on src/main/resources/plugin.yaml
> +  issues: https://github.com/halo-dev/plugin-starter/issues
```suggestion
  homepage: https://github.com/halo-sigs/plugin-sticker#readme
  repo: https://github.com/halo-sigs/plugin-sticker
  issues: https://github.com/halo-sigs/plugin-sticker/issues
```

2024-07-22 03:08 UTC, LIlGG commented on src/main/resources/plugin.yaml
> +      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
```suggestion
      url: "https://github.com/halo-sigs/plugin-sticker/blob/main/LICENSE"
```

2024-07-22 03:08 UTC, LIlGG commented on ui/package.json
> +    "npm-run-all2": "^6.2.0",
无用的包。

```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on ui/package.json
> +    "prettier": "^3.3.2",
需要增加对应的配置

```suggestion
    "prettier": "^3.3.2",
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/editor/index.ts
> +}
Halo 本身导出了 `ExtensionOptions` 接口，这里可以直接使用，不用再重新定义。

```suggestion
export interface StickerOptions {
  inline: boolean;
  HTMLAttributes: Record<string, any>;
}
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/editor/index.ts
> +const StickerExtension = Node.create<StickerOptions>({
```suggestion
const StickerExtension = Node.create<ExtensionOptions & StickerOptions>({
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/editor/index.ts
> +  draggable: true,
Halo 中重写了拖拽功能，因此使用此属性无用，需要使用 `ExtensionOptions` 中的 `getDraggable` 进行扩展。

```
// 拖拽扩展
getDraggable?: ({ editor }: { editor: Editor }) => DraggableItem | boolean;
```

```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/editor/index.ts
> +  //@ts-ignore
这里应该不需要使用 `//@ts-ignore` 。 Halo 编辑器还导出了 `CoreEditor` 用于 PMEditor 类型，默认导出的 `Editor` 是 Vue 相关的。
```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/editor/index.ts
> +      },
似乎无用

```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/editor/index.ts
> +  //@ts-ignore
同上，不需要 `@ts-ignore`
```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on ui/src/views/HomeView.vue
> +});
建议移除

```suggestion
```

2024-07-22 03:08 UTC, LIlGG commented on ui/package.json
> +    "canvas-confetti": "^1.9.3",
建议移除
```suggestion
```

2024-07-23 02:46 UTC, LIlGG commented on ui/src/editor/index.ts
> +}
建议使用下面的方式提供类型

```suggestion
declare module "@halo-dev/richtext-editor" {
  interface Commands<ReturnType> {
    sticker: {
      openStickerPicker: (tr: Transaction) => ReturnType;
    };
  }
}
```

2024-07-23 02:46 UTC, LIlGG commented on ui/src/editor/index.ts
> +  (editor.commands as ExtendedSingleCommands).openStickerPicker(
使用 `interface Commands<ReturnType>` 扩展类型后，直接使用下面的代码即可
```suggestion
  editor.commands.openStickerPicker(
```

2024-07-23 04:01 UTC, ruibaby requested changes

2024-07-23 04:01 UTC, ruibaby commented on .github/workflows/ci.yaml
> +      ui-path: "ui"
建议指定一下 node-version 和 pnpm-version，这个 CI 默认应该是 Node 18、pnpm 8。

```
node-version: 20
pnpm-version: 9
```

2024-07-23 04:01 UTC, ruibaby commented on build.gradle
> +group 'run.halo.starter'
修改包名和这个 group。

2024-07-23 04:01 UTC, ruibaby commented on src/main/java/run/halo/starter/StickerPlugin.java
> + */
移除或修改信息。

2024-07-23 04:01 UTC, ruibaby commented on src/main/resources/plugin.yaml
> +  name: plugin-sticker
```suggestion
  name: sticker
```

kind 和 apiVersion 已经可以用于区分是 Plugin 资源，所以没有必要在添加 plugin- 前缀。

2024-07-23 04:01 UTC, ruibaby commented on src/main/resources/plugin.yaml
> +  description: "支持官方编辑器添加表情包"
```suggestion
  description: "为默认编辑器添加表情包的支持"
```

2024-07-23 04:01 UTC, ruibaby commented on ui/src/views/HomeView.vue
可以直接移除掉这个页面，或者移除掉代码，后续需要的时候再添加。

2024-07-25 03:23 UTC, LIlGG approved these changes
/lgtm

2024-07-25 03:26 UTC, ruibaby approved these changes
/approve

2024-07-25 03:29 UTC, merged