feat: upload sticker backend api
halo-sigs/plugin-sticker pull request #2
Opened 2024-09-15 15:58 UTC by AirboZH

2024-09-15 16:11 UTC, AirboZH commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +        stickerStatus.setDisplayName(attachment.getMetadata().getName());
这一块内容有没有什么简单一点的写法呢，我试过 Lombok 的 `@Builder` 注解，好像和空构造方法有冲突。

2024-09-16 03:35 UTC, LIlGG requested changes
发现一些问题，可以修改一下。

另外我发现目前没有鉴权配置及用户中心相关接口。

这意味着只有超级管理员能够访问此接口。

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/StickerPlugin.java
> +        schemeManager.unregister(schemeManager.get(StickerGroup.class));
建议使用如下写法，防止插件启动失败后产生无法找到资源的错误。

```suggestion
        schemeManager.unregister(Scheme.buildFromType(Sticker.class));
        schemeManager.unregister(Scheme.buildFromType(StickerGroup.class));
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +            .GET("sticker/test", this::test)
移除无用的内容

```suggestion
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +    }
同上，移除。

```suggestion
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +            .POST("sticker/{groupName}/upload", contentType(MediaType.MULTIPART_FORM_DATA),
不是很符合 API 相关规则，对于 `sticker` 的上传，建议使用 `stickers/-/upload` 表示此上传接口。在参数中提供 `groupName` 即可。

>  `/apis/<group>/<version>/<resource>[/<resourceName>/<subresource>] `

```suggestion
            .POST("sticker/{groupName}/upload", contentType(MediaType.MULTIPART_FORM_DATA),
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +        return CustomEndpoint.super.groupVersion();
使用具体的 `groupVersion`，例如 `console.api.sticker.halo.run/v1alpha1`

```suggestion
        return GroupVersion.parseAPIVersion("console.api.sticker.halo.run/v1alpha1`");
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +        sticker.setMetadata(attachment.getMetadata());
使用 UUID 随机生成。

```suggestion
        sticker.setMetadata(UUID.randomUUID().toString());
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +        stickerStatus.setDisplayName(attachment.getMetadata().getName());
这段放入 `attachment.getMetadata().getName()` 似乎没有任何意义。

```suggestion
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +        stickerSpec.setName(attachment.getMetadata().getName());
建议改个名，name 表达的意义不明确。

```suggestion
        stickerSpec.setName(attachment.getMetadata().getName());
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +    }
不是特别理解，这里的做法。意思是如果 `groupName` 不存在，则使用 `.user-` + 用户 metadataname 的方式创建一个？？

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/model/Sticker.java
> +    public static final String KIND = "Sticker";
似乎没有其他位置使用此 `KIND`，因此直接使用 ` kind = Sticker` 即可。

```suggestion
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/model/Sticker.java
> +        private Integer sequence;
个人觉得这两个不应该算 `status`，应当放置在 `spec` 中。

```suggestion
```

2024-09-16 03:35 UTC, LIlGG commented on src/main/java/run/halo/sticker/service/StickerService.java
> +}
用不到的话暂时删除。

2024-09-16 03:37 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +        stickerStatus.setDisplayName(attachment.getMetadata().getName());
这块没有什么简单的写法。这里只需要一个 `attachment.getMetadata().getName()` 外部数据，所以只需要传入 attachmentName 即可。

2024-09-16 03:45 UTC, AirboZH commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +    }
我的计划是每个表情包都有自己的一个分组，这个分组可以是用户自己的分组，也可以是管理员创建的分组，区别在于isPublic。
如果是用户上传到用户自己的表情包当中就新建一个这样的分组，如果是管理员创建的表情合集就通过stickerGroup的接口创建一个public的分组然后上传到这个分组当中。
所以，如果是一个新用户直接上传一个表情，就会用该用户的名字创建一个分组。

2024-09-16 04:02 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerAttachmentEndpoint.java
> +    }
> 我的计划是每个表情包都有自己的一个分组，这个分组可以是用户自己的分组，也可以是管理员创建的分组，区别在于isPublic。 如果是用户上传到用户自己的表情包当中就新建一个这样的分组，如果是管理员创建的表情合集就通过stickerGroup的接口创建一个public的分组然后上传到这个分组当中。 所以，如果是一个新用户直接上传一个表情，就会用该用户的名字创建一个分组。

那我觉得这个做法可能有点问题。不应该以用户名为组的 metadataName。

而应该是表情包组中的 `spec` 或者 `label` 中包含这个 userName。这样后续如果想查询此表情包组属于哪个用户也更容易一些。

2024-09-22 12:45 UTC, LIlGG requested changes

2024-09-22 12:45 UTC, LIlGG commented on src/main/java/run/halo/sticker/pojo/query/StickerQuery.java
> +    }
建议使用 Halo 提供的 `SortableRequest` 类来实现排序，而不是自行实现。

2024-09-22 12:45 UTC, LIlGG commented on src/main/java/run/halo/sticker/endpoint/StickerEndpoint.java
> +            .flatMap(stickers -> ServerResponse.ok().bodyValue(stickers));
这里应该是查询 `Sticker` 的分页数据吧。我认为使用 `stickerService` 更恰当一些。

2024-09-22 12:45 UTC, LIlGG commented on src/main/java/run/halo/sticker/reconciler/StickerReconciler.java
> +    }
不理解这里的作用？是想计算当前组下有多少表情？？似乎有些抽象了，完全没必要。

2024-09-22 12:45 UTC, LIlGG commented on src/main/java/run/halo/sticker/service/impl/StickerGroupServiceImpl.java
> +        return this.client.list(Sticker.class, StickersListPredicate(query),
推荐使用 `client.listBy` 来进行分页查询。

2024-09-28 09:12 UTC, LIlGG approved these changes
/lgtm

2024-09-28 09:13 UTC, merged